from datetime import datetime
from typing import Dict, Any, List


def _choose_recommendation(score: float) -> Dict[str, str]:
    if score <= 30:
        return {"code": "APPROVE", "label": "APPROVE", "color": "#00C853"}
    if score <= 55:
        return {"code": "REVIEW", "label": "MANUAL REVIEW", "color": "#FF9500"}
    if score <= 75:
        return {"code": "HOLD", "label": "HOLD APPLICATION", "color": "#FF6B00"}
    return {"code": "REJECT", "label": "REJECT + FILE STR", "color": "#FF3B3B"}


def _pick_specific_reason(nlp_flags: List[str], vit_score: float) -> str:
    flags = [f.lower() for f in (nlp_flags or [])]
    if any("struck" in f or "struck off" in f for f in flags):
        return "Submitting company is struck off in MCA21 registry — legally cannot conduct business in India"
    if any("mortgag" in f or "mortgaged" in f for f in flags):
        return "Collateral property already mortgaged — duplicate pledge detected"
    if any("future date" in f or "post-dated" in f or "date inconsistency" in f for f in flags):
        return "Document contains post-dated entries — possible backdating fraud"
    if vit_score > 70:
        return "Pixel-level analysis detected image manipulation artifacts"
    return "Multiple low-level anomalies detected across analysis layers"


def _regulatory_reference(code: str) -> str:
    if code == "APPROVE":
        return "Document meets RBI Master Direction on KYC (2016, updated 2024) requirements"
    if code == "REVIEW":
        return "As per RBI Circular on Fraud Risk Management — manual verification required for anomalous documents"
    if code == "HOLD":
        return "RBI Master Direction on Frauds — fresh document collection mandatory when inconsistencies detected"
    return "As per RBI Circular RBI/2015-16/418 — STR filing with FIU-IND mandatory within 7 days of fraud detection"


NEXT_STEPS = {
    "APPROVE": [
        "Proceed with standard loan processing workflow",
        "Complete KYC verification as per RBI guidelines",
        "Obtain credit bureau report (CIBIL/Experian)",
        "Document approval in loan origination system"
    ],
    "REVIEW": [
        "Escalate file to Senior Credit Officer for physical verification",
        "Request original documents from applicant",
        "Cross-verify company details on MCA21 portal",
        "Complete enhanced due diligence checklist"
    ],
    "HOLD": [
        "Communicate requirement for fresh documents to applicant",
        "Issue document deficiency notice within 2 working days",
        "Do NOT process application until fresh documents received",
        "Record reason for hold in loan origination system"
    ],
    "REJECT": [
        "Reject application immediately — do not process further",
        "File Suspicious Transaction Report (STR) with FIU-IND within 7 days",
        "Preserve all submitted documents as evidence",
        "Report to bank's internal fraud risk management team",
        "Block applicant PAN in bank's fraud registry"
    ]
}


def _build_str_template(today: str, branch_name: str, filename: str, final_score: float, specific_reason: str, nlp_flags: List[str]) -> str:
    flags_text = "\n".join(nlp_flags or []) if nlp_flags else "None"
    return f"SUSPICIOUS TRANSACTION REPORT — FIU-IND\nDate: {today}\nReporting Entity: Canara Bank\nBranch: {branch_name}\n\nSuspect Details:\nDocument Submitted: {filename}\nRisk Score: {final_score}%\n\nNature of Suspicion:\n{specific_reason}\n\nFlags Detected:\n{flags_text}\n\nRecommended Action: Reject loan application and investigate applicant.\n\nGenerated by: NetraAI ForgeShield v1.0"


def generate_decision(scan_result: Dict[str, Any]) -> Dict[str, Any]:
    """Generate an underwriter decision from a full scan result dict.

    Expected keys on input: final_score (float), nlp_flags (list), vit_score (float), filename (str)
    """
    start = datetime.utcnow()
    final_score = float(scan_result.get("final_score") or scan_result.get("risk_score") or 0.0)
    nlp_flags = scan_result.get("nlp_flags") or []
    vit_score = float(scan_result.get("vit_score") or 0.0)
    filename = scan_result.get("filename") or scan_result.get("file_name") or "unknown"

    rec = _choose_recommendation(final_score)
    specific_reason = _pick_specific_reason(nlp_flags, vit_score)
    regulatory_reference = _regulatory_reference(rec["code"])
    next_steps = NEXT_STEPS.get(rec["code"], [])

    str_template = None
    if rec["code"] == "REJECT":
        today = datetime.utcnow().date().isoformat()
        # Branch name not always available — use placeholder
        branch_name = scan_result.get("branch_name") or "[Branch Name]"
        str_template = _build_str_template(today, branch_name, filename, final_score, specific_reason, nlp_flags)

    end = datetime.utcnow()
    processing_time_seconds = (end - start).total_seconds()

    return {
        "recommendation": rec,
        "specific_reason": specific_reason,
        "regulatory_reference": regulatory_reference,
        "next_steps": next_steps,
        "str_template": str_template,
        "processing_time_seconds": processing_time_seconds
    }
